import type { Metadata } from "next";
import { Fjalla_One, Raleway, } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/common/header";


const fjallaOne = Fjalla_One({
  weight: ["400"],
  variable: "--font-fjalla-one",
  subsets: ["latin"],
})

const raleway = Raleway({
  weight: ["300"],
  variable: "--font-raleway",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${fjallaOne.variable} ${raleway.variable} antialiased`}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
