import type { Metadata } from "next";
import { Fjalla_One, Raleway, } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/common/header";
import { Footer } from "@/components/common/footer";
import { ClerkProvider } from "@clerk/nextjs";


const fjallaOne = Fjalla_One({
  weight: ["400"],
  variable: "--font-fjalla-one",
  subsets: ["latin"],
})

const raleway = Raleway({
  weight: ["500"],
  variable: "--font-raleway",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning
      >
        <body className={`${fjallaOne.variable} ${raleway.variable} antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
